default: &default
  classifiers_dir: <%= ENV['CLASSIFIERS_DIR'] || "/home/whiz/workspace/clients_and_servers/classifiers" %>
  pretrained_vectors_dir: <%= ENV['PRETRAINED_VECTORS_DIR'] || "/home/whiz/workspace/clients_and_servers/wiki" %>
  fast_text_path: "/home/whiz/workspace/clients_and_servers/fasttext/fastText-0.2.0"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  fast_text_path: "../../../fastText"

production:
  <<: *default
