slack_druid_data_model_api_url:     http://10.0.11.5:4000/api/dataSources
slack_druid_sign_in_api_url:        http://10.0.11.5:4000/api/auth/sign_in
training_api_url:                   http://mlnlp.whiz.ai:3200/api
email: admin@whiz.ai
password: 12345678